const CFG={base:'https://resultados.tse.jus.br/oficial/ele2026',federal:'6257',estadual:'6259',poll:60000,start:new Date('2026-10-04T17:00:00-03:00')};
const UFS={ac:'Acre',al:'Alagoas',ap:'Amapá',am:'Amazonas',ba:'Bahia',ce:'Ceará',df:'Distrito Federal',es:'Espírito Santo',go:'Goiás',ma:'Maranhão',mt:'Mato Grosso',ms:'Mato Grosso do Sul',mg:'Minas Gerais',pa:'Pará',pb:'Paraíba',pr:'Paraná',pe:'Pernambuco',pi:'Piauí',rj:'Rio de Janeiro',rn:'Rio Grande do Norte',rs:'Rio Grande do Sul',ro:'Rondônia',rr:'Roraima',sc:'Santa Catarina',sp:'São Paulo',se:'Sergipe',to:'Tocantins'};
let view='br',uf='ba',mun='',munName='',munCache=null;const $=s=>document.querySelector(s),cards=$('#cards'),notice=$('#notice'),filters=$('#filters'),stateSel=$('#stateSelect'),citySel=$('#citySelect');
function election(cargo){return cargo===1?CFG.federal:CFG.estadual}function resultUrl(scope,cargo,opt={}){let e=election(cargo),c=String(cargo).padStart(4,'0');if(scope==='br')return `${CFG.base}/${e}/dados/br/br-c${c}-e0${e}-u.json`;let u=(opt.uf||uf).toLowerCase(),m=opt.mun||'';if(u==='zz')return m?`${CFG.base}/${e}/dados/zz/zz${m}-c${c}-e0${e}-u.json`:`${CFG.base}/${e}/dados/zz/zz-c${c}-e0${e}-u.json`;return m?`${CFG.base}/${e}/dados/${u}/${u}${m}-c${c}-e0${e}-u.json`:`${CFG.base}/${e}/dados/${u}/${u}-c${c}-e0${e}-u.json`}
function fmt(n){return Number(n||0).toLocaleString('pt-BR')}function num(v){return Number(String(v??0).replace(',','.'))||0}function pct(v){return num(v).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})+'%'}function candidates(j){let c=j?.cand||j?.candidatos||j?.abr?.[0]?.cand||[];return Array.isArray(c)?c:[]}function progress(j){for(const x of [j?.pst,j?.psi,j?.s?.pst,j?.abr?.[0]?.pst])if(x!=null)return pct(x);return 'Aguardando'}function isElectionTime(){return Date.now()>=CFG.start.getTime()}
function card(label,j){let c=candidates(j);if(!c.length)return `<article class="card"><h2>${label}</h2><div class="empty">Aguardando dados oficiais da totalização.</div><div class="progress">Seções totalizadas: ${progress(j)}</div></article>`;return `<article class="card"><h2>${label}</h2>${c.slice(0,label.includes('DEPUTADO')?16:10).map(x=>{let p=x.pvap??x.pvapt??x.pvapc??0,n=x.nm||x.n||x.nmu||'Candidato',pt=x.cc||x.sg||x.part||'',v=x.vap??x.v??0;return `<div class="candidate"><div class="row"><div><div class="name">${n}</div><div class="party">${pt} · ${fmt(v)} votos</div></div><div class="pct">${pct(p)}</div></div><div class="bar"><i style="width:${Math.min(100,num(p))}%"></i></div></div>`}).join('')}<div class="progress">Seções totalizadas: ${progress(j)}</div></article>`}
async function get(u){let r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}
function jobs(){if(view==='br')return [['PRESIDENTE · BRASIL',resultUrl('br',1)]];if(view==='exterior'){let loc=mun?munName:'EXTERIOR';return [[`PRESIDENTE · ${loc}`,resultUrl('geo',1,{uf:'zz',mun})]]}let loc=mun?munName:UFS[uf].toUpperCase();return [['PRESIDENTE · '+loc,resultUrl('geo',1,{uf,mun})],['GOVERNADOR · '+loc,resultUrl('geo',3,{uf,mun})],['SENADOR · '+loc+' · 2 VAGAS',resultUrl('geo',5,{uf,mun})],['DEPUTADO FEDERAL · '+loc,resultUrl('geo',6,{uf,mun})],[(uf==='df'?'DEPUTADO DISTRITAL':'DEPUTADO ESTADUAL')+' · '+loc,resultUrl('geo',7,{uf,mun})]]}
function preview(){cards.innerHTML=[card('PRESIDENTE · BRASIL',{}),card('GOVERNADOR · BAHIA',{}),card('SENADOR · BAHIA · 2 VAGAS',{})].join('');$('#status').textContent='PRÉVIA · SEM VOTOS';$('#health').textContent='Interface em teste';notice.textContent='PRÉVIA VISUAL: esta tela não contém votos simulados. Serve apenas para conferir o layout.'}
function walk(o,out=[]){if(!o||typeof o!=='object')return out;if(!Array.isArray(o)){let code=o.cd??o.cdm??o.cdmun??o.codigo,n=o.nm??o.nmmun??o.nome,u=(o.sg??o.uf??o.sgua??'').toString().toLowerCase();if(code&&n&&String(code).match(/^\d{4,5}$/))out.push({code:String(code).padStart(5,'0'),name:String(n),uf:u})}for(const v of Object.values(o))if(v&&typeof v==='object')walk(v,out);return out}
async function municipalities(){if(munCache)return munCache;try{let j=await get(`${CFG.base}/${CFG.federal}/config/mun-e0${CFG.federal}-cm.json`),a=walk(j),seen=new Set();munCache=a.filter(x=>{let k=x.uf+x.code;if(seen.has(k))return false;seen.add(k);return true});return munCache}catch(e){return []}}
async function fillCities(targetUf){citySel.innerHTML='<option value="">Todas as localidades</option>';let a=(await municipalities()).filter(x=>x.uf===targetUf).sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));for(const x of a){let o=document.createElement('option');o.value=x.code;o.textContent=x.name;citySel.appendChild(o)}}
async function configure(){filters.classList.toggle('hidden',view==='br'||view==='demo');$('#stateBox').classList.toggle('hidden',view==='exterior');$('#cityBox').classList.toggle('hidden',view==='states');if(view==='states'){mun='';munName=''}if(view==='cities'){await fillCities(uf);citySel.value=mun}if(view==='exterior'){uf='zz';mun='';munName='';await fillCities('zz')}}
async function load(){if(view==='demo'){preview();return}if(!isElectionTime()){cards.innerHTML=jobs().map(([l])=>card(l,{})).join('');$('#status').textContent='AGUARDANDO 17H';$('#health').textContent='Em espera';return}let ok=0,out=[];for(const [label,u] of jobs()){try{let j=await get(u);out.push(card(label,j));ok++}catch(e){out.push(card(label,{}))}}cards.innerHTML=out.join('');$('#updated').textContent='Última consulta: '+new Date().toLocaleTimeString('pt-BR',{timeZone:'America/Sao_Paulo'});if(ok){$('#status').textContent='DADOS OFICIAIS TSE';$('#health').textContent='Conectado';notice.textContent='Resultados parciais conforme arquivos oficiais do TSE. Os números podem mudar durante a totalização.'}else{$('#status').textContent='TSE INDISPONÍVEL';$('#health').textContent='Tentando novamente';notice.textContent='Os arquivos oficiais não responderam nesta consulta. Nenhum dado foi estimado; nova tentativa automática em instantes.'}}
for(const [k,n] of Object.entries(UFS)){let o=document.createElement('option');o.value=k;o.textContent=n;stateSel.appendChild(o)}stateSel.value='ba';
stateSel.onchange=async()=>{uf=stateSel.value;mun='';munName='';if(view==='cities')await fillCities(uf);load()};citySel.onchange=()=>{mun=citySel.value;munName=citySel.options[citySel.selectedIndex]?.textContent||'';load()};
document.querySelectorAll('nav button').forEach(b=>b.onclick=async()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view;if(view==='states'||view==='cities'){if(uf==='zz')uf='ba';stateSel.value=uf}await configure();load()});
document.querySelectorAll('.quick button').forEach(b=>b.onclick=async()=>{let q=b.dataset.quick;if(q==='zz'){view='exterior';document.querySelector('[data-view="exterior"]').click();return}view=q==='salvador'||q==='lauro'?'cities':'states';uf=q==='sp'?'sp':q==='mg'?'mg':q==='df'?'df':'ba';mun=q==='salvador'?'38490':q==='lauro'?'36854':'';munName=q==='salvador'?'SALVADOR':q==='lauro'?'LAURO DE FREITAS':'';document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===view));stateSel.value=uf;await configure();if(mun&&!Array.from(citySel.options).some(o=>o.value===mun)){let o=document.createElement('option');o.value=mun;o.textContent=munName;citySel.appendChild(o)}citySel.value=mun;load()});
function tick(){let d=CFG.start-new Date();if(d>0){let h=Math.floor(d/36e5),m=Math.floor(d%36e5/6e4),s=Math.floor(d%6e4/1000);$('#countdown').textContent=`${h}h ${String(m).padStart(2,'0')}m ${String(s).padStart(2,'0')}s para 17h`}else $('#countdown').textContent='Apuração liberada pelo TSE'}setInterval(load,CFG.poll);setInterval(()=>{$('#clock').textContent=new Date().toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'});tick()},1000);tick();load();